// Package CerberusApi provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"net/http"
	"strings"
)

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {

	// The new password to set.
	NewPassword string `json:"new_password"`

	// The old or existing password
	OldPassword string `json:"old_password"`
}

// Claim defines model for Claim.
type Claim struct {

	// A short dercription about the claim.
	Description *string `json:"description,omitempty"`

	// Internal identifier of the claim
	Id int `json:"id"`

	// A alphanumeric name, to represent claim name in OAuth2 claim.
	Name string `json:"name"`
}

// ClaimPage defines model for ClaimPage.
type ClaimPage struct {
	// Embedded fields due to inline allOf schema

	// an array of claims
	Claims []Claim `json:"claims"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// Error defines model for Error.
type Error struct {

	// Detail description
	Description *string `json:"description,omitempty"`

	// Error code
	Error *string `json:"error,omitempty"`
}

// Page defines model for Page.
type Page struct {

	// Page number of the response chunk
	PageNumber int32 `json:"page_number"`

	// Total available pages
	PageTotal int32 `json:"page_total"`
}

// Scope defines model for Scope.
type Scope struct {

	// A short dercription about the scope.
	Description *string `json:"description,omitempty"`

	// Internal identifier of the scope
	Id int `json:"id"`

	// Scope name. alphanumeric characters only.
	Name string `json:"name"`
}

// ServiceProvider defines model for ServiceProvider.
type ServiceProvider struct {

	// Kind of the application. The default, if omitted, is web. The defined values are native or web. Web Clients using the OAuth Implicit Grant Type MUST only register URLs using the https scheme as redirect_uris; they MUST NOT use localhost as the hostname. Native Clients MUST only register redirect_uris using custom URI schemes or URLs using the http: scheme with localhost as the hostname. Authorization Servers MAY place additional constraints on Native Clients. Authorization Servers MAY reject Redirection URI values using the http scheme, other than the localhost case for Native Clients. The Authorization Server MUST verify that all the registered redirect_uris conform to these constraints. This prevents sharing a Client ID across different types of Clients.
	ApplicationType string `json:"application_type"`

	// JSON array containing a list of the OAuth 2.0 Grant Types that the Client is declaring that it will restrict itself to using. The Grant Type values used by
	//
	// OpenID Connect are:
	// 1. authorization_code: The Authorization Code Grant Type described in OAuth 2.0 Section 4.1.
	// 1. implicit: The Implicit Grant Type described in OAuth 2.0 Section 4.2.
	// 1. refresh_token: The Refresh Token Grant Type described in OAuth 2.0 Section 6.
	//
	// The following table lists the correspondence between response_type values that the Client will use and grant_type values that MUST be included in the registered grant_types list:
	//
	// 1. code: authorization_code
	// 1. id_token: implicit
	// 1. token id_token: implicit
	// 1. code id_token: authorization_code, implicit
	// 1. code token: authorization_code, implicit
	// 1. code token id_token: authorization_code, implicit
	//
	// If omitted, the default is that the Client will use only the authorization_code Grant Type.
	GrantTypes []string `json:"grant_types"`

	// Name of the Client to be presented to the End-User. If desired, representation of this Claim in different languages and scripts is represented as described in Section 2.1.
	Name *string `json:"name,omitempty"`

	// Array of Redirection URI values used by the Client. One of these registered Redirection URI values MUST exactly match the redirect_uri parameter value used in each Authorization Request, with the matching performed as described in Section 6.2.1 of [RFC3986] (Simple String Comparison).
	RedirectUris []string `json:"redirect_uris"`
}

// ServiceProviderCredentials defines model for ServiceProviderCredentials.
type ServiceProviderCredentials struct {

	// Client identifier
	ClientId string `json:"client_id"`

	// Client secret
	ClientSecret string `json:"client_secret"`
}

// ServiceProviderSummary defines model for ServiceProviderSummary.
type ServiceProviderSummary struct {

	// Identifier of the provider.
	Id int `json:"id"`
}

// ServiceProviderSummaryPage defines model for ServiceProviderSummaryPage.
type ServiceProviderSummaryPage struct {
	// Embedded fields due to inline allOf schema

	// An array of service provider summary in one page.
	ServiceProviders []ServiceProviderSummary `json:"service_providers"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// User defines model for User.
type User struct {
	// Embedded fields due to inline allOf schema

	// End-User's preferred postal address. The value of the address member is a JSON [RFC4627] structure containing some or all of the members defined in Section 5.1.1.
	Address *UserAddress `json:"address,omitempty"`

	// End-User's birthday, represented as an ISO 8601:2004 [ISO8601‑2004] YYYY-MM-DD format. The year MAY be 0000, indicating that it is omitted. To represent only the year, YYYY format is allowed. Note that depending on the underlying platform's date related function, providing just year can result in varying month and day, so the implementers need to take this factor into account to correctly process the dates.
	Birthdate *openapi_types.Date `json:"birthdate,omitempty"`

	// End-User's gender. Values defined by this specification are female and male. Other values MAY be used when neither of the defined values are applicable.
	Gender *string `json:"gender,omitempty"`

	// User identifier.
	Id int `json:"id"`

	// End-User's locale, represented as a BCP47 [RFC5646] language tag. This is typically an ISO 639-1 Alpha-2 [ISO639‑1] language code in lowercase and an ISO 3166-1 Alpha-2 [ISO3166‑1] country code in uppercase, separated by a dash. For example, en-US or fr-CA. As a compatibility note, some implementations have used an underscore as the separator rather than a dash, for example, en_US; Relying Parties MAY choose to accept this locale syntax as well.
	Locale *string `json:"locale,omitempty"`

	// Username for login
	Username string `json:"username"`

	// String from zoneinfo [zoneinfo] time zone database representing the End-User's time zone. For example, Europe/Paris or America/Los_Angeles.
	Zoneinfo *string `json:"zoneinfo,omitempty"`
	// Embedded struct due to allOf(#/components/schemas/UserName)
	UserName
	// Embedded struct due to allOf(#/components/schemas/UserProfile)
	UserProfile
	// Embedded struct due to allOf(#/components/schemas/UserContact)
	UserContact
	// Embedded struct due to allOf(#/components/schemas/UserAddress)
	UserAddress
}

// UserAddress defines model for UserAddress.
type UserAddress struct {

	// Country name component.
	Country *string `json:"country,omitempty"`

	// Full mailing address, formatted for display or use on a mailing label. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair ("\r\n") or as a single line feed character ("\n").
	Formatted *string `json:"formatted,omitempty"`

	// City or locality component.
	Locality *string `json:"locality,omitempty"`

	// Zip code or postal code component.
	PostalCode *string `json:"postal_code,omitempty"`

	// State, province, prefecture, or region component.
	Region *string `json:"region,omitempty"`

	// Full street address component, which MAY include house number, street name, Post Office Box, and multi-line extended street address information. This field MAY contain multiple lines, separated by newlines. Newlines can be represented either as a carriage return/line feed pair ("\r\n") or as a single line feed character ("\n").
	StreetAddress *string `json:"street_address,omitempty"`
}

// UserContact defines model for UserContact.
type UserContact struct {

	// End-User's preferred e-mail address. Its value MUST conform to the RFC 5322 [RFC5322] addr-spec syntax. The RP MUST NOT rely upon this value being unique, as discussed in Section 5.7.
	Email *string `json:"email,omitempty"`

	// True if the End-User's e-mail address has been verified; otherwise false. When this Claim Value is true, this means that the OP took affirmative steps to ensure that this e-mail address was controlled by the End-User at the time the verification was performed. The means by which an e-mail address is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating.
	EmailVerified *bool `json:"email_verified,omitempty"`

	// End-User's preferred telephone number. E.164 [E.164] is RECOMMENDED as the format of this Claim, for example, +1 (425) 555-1212 or +56 (2) 687 2400. If the phone number contains an extension, it is RECOMMENDED that the extension be represented using the RFC 3966 [RFC3966] extension syntax, for example, +1 (604) 555-1234;ext=5678.
	PhoneNumber *string `json:"phone_number,omitempty"`

	// User at the time the verification was performed. The means by which a phone number is verified is context-specific, and dependent upon the trust framework or contractual agreements within which the parties are operating. When true, the phone_number Claim MUST be in E.164 format and any extensions MUST be represented in RFC 3966 format.
	PhoneNumberVerified *bool `json:"phone_number_verified,omitempty"`
}

// UserName defines model for UserName.
type UserName struct {

	// Surname(s) or last name(s) of the End-User. Note that in some cultures, people can have multiple family names or no family name; all can be present, with the names being separated by space characters.
	FamilyName *string `json:"family_name,omitempty"`

	// Given name(s) or first name(s) of the End-User. Note that in some cultures, people can have multiple given names; all can be present, with the names being separated by space characters.
	GivenName *string `json:"given_name,omitempty"`

	// Middle name(s) of the End-User. Note that in some cultures, people can have multiple middle names; all can be present, with the names being separated by space characters. Also note that in some cultures, middle names are not used.
	MiddleName *string `json:"middle_name,omitempty"`

	// End-User's full name in displayable form including all name parts, possibly including titles and suffixes, ordered according to the End-User's locale and preferences.
	Name *string `json:"name,omitempty"`

	// Casual name of the End-User that may or may not be the same as the given_name. For instance, a nickname value of Mike might be returned alongside a given_name value of Michael.
	Nickname *string `json:"nickname,omitempty"`

	// Shorthand name by which the End-User wishes to be referred to at the RP, such as janedoe or j.doe. This value MAY be any valid JSON string including special characters such as @, /, or whitespace. The RP MUST NOT rely upon this value being unique.
	PreferredUsername *string `json:"preferred_username,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {

	// URL of the End-User's profile picture. This URL MUST refer to an image file (for example, a PNG, JPEG, or GIF image file), rather than to a Web page containing an image. Note that this URL SHOULD specifically reference a profile photo of the End-User suitable for displaying when describing the End-User, rather than an arbitrary photo taken by the End-User.
	Picture *string `json:"picture,omitempty"`

	// URL of the End-User's profile page. The contents of this Web page SHOULD be about the End-User.
	Profile *string `json:"profile,omitempty"`

	// URL of the End-User's Web page or blog. This Web page SHOULD contain information published by the End-User or an organization that the End-User is affiliated with.
	Website *string `json:"website,omitempty"`
}

// UserRecoverPassword defines model for UserRecoverPassword.
type UserRecoverPassword struct {

	// Email id of the user to confirm with user store
	Email string `json:"email"`

	// Username of the user
	Username string `json:"username"`
}

// UserResetPassword defines model for UserResetPassword.
type UserResetPassword struct {

	// One time password received through initiation process
	Otp string `json:"otp"`

	// Username of the user
	Username string `json:"username"`
}

// UserStatusUpdate defines model for UserStatusUpdate.
type UserStatusUpdate struct {

	// New status to change to.
	Active bool `json:"active"`
}

// UserSummary defines model for UserSummary.
type UserSummary struct {

	// User is active or inactive
	Active *bool `json:"active,omitempty"`

	// User is blocked by invalid attempt
	Blocked *bool `json:"blocked,omitempty"`

	// Email address
	Email *string `json:"email,omitempty"`

	// Login username
	Username *string `json:"username,omitempty"`
}

// UserSummaryPage defines model for UserSummaryPage.
type UserSummaryPage struct {
	// Embedded fields due to inline allOf schema

	// A collection of users
	Users []UserSummary `json:"users"`
	// Embedded struct due to allOf(#/components/schemas/Page)
	Page
}

// UnAuthorized defines model for UnAuthorized.
type UnAuthorized Error

// GetClaimsParams defines parameters for GetClaims.
type GetClaimsParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateClaimJSONBody defines parameters for CreateClaim.
type CreateClaimJSONBody Claim

// UpdateClaimJSONBody defines parameters for UpdateClaim.
type UpdateClaimJSONBody Claim

// GetScopesParams defines parameters for GetScopes.
type GetScopesParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateScopeJSONBody defines parameters for CreateScope.
type CreateScopeJSONBody Scope

// UpdateScopeJSONBody defines parameters for UpdateScope.
type UpdateScopeJSONBody Scope

// GetServiceProvidersParams defines parameters for GetServiceProviders.
type GetServiceProvidersParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateServiceProviderJSONBody defines parameters for CreateServiceProvider.
type CreateServiceProviderJSONBody ServiceProvider

// UpdateServiceProviderJSONBody defines parameters for UpdateServiceProvider.
type UpdateServiceProviderJSONBody ServiceProvider

// GenerateCredentialsParams defines parameters for GenerateCredentials.
type GenerateCredentialsParams struct {

	// Indicates wheather to refresh the client_id of not. Default is `false`.
	RefreshId *bool `json:"refresh_id,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {

	// Number of items in each page.
	// Default value is 10.
	PageSize *int `json:"page_size,omitempty"`

	// Page number to return in response.
	// Starts with 1 and default value is 1 too.
	PageNumber *int `json:"page_number,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody User

// InitiatePasswordRecoveryJSONBody defines parameters for InitiatePasswordRecovery.
type InitiatePasswordRecoveryJSONBody UserRecoverPassword

// ResetUserPasswordJSONBody defines parameters for ResetUserPassword.
type ResetUserPasswordJSONBody UserResetPassword

// UpdateUserJSONBody defines parameters for UpdateUser.
type UpdateUserJSONBody User

// ChangeUserPasswordJSONBody defines parameters for ChangeUserPassword.
type ChangeUserPasswordJSONBody ChangePasswordRequest

// UpdateUserStatusJSONBody defines parameters for UpdateUserStatus.
type UpdateUserStatusJSONBody UserStatusUpdate

// CreateClaimRequestBody defines body for CreateClaim for application/json ContentType.
type CreateClaimJSONRequestBody CreateClaimJSONBody

// UpdateClaimRequestBody defines body for UpdateClaim for application/json ContentType.
type UpdateClaimJSONRequestBody UpdateClaimJSONBody

// CreateScopeRequestBody defines body for CreateScope for application/json ContentType.
type CreateScopeJSONRequestBody CreateScopeJSONBody

// UpdateScopeRequestBody defines body for UpdateScope for application/json ContentType.
type UpdateScopeJSONRequestBody UpdateScopeJSONBody

// CreateServiceProviderRequestBody defines body for CreateServiceProvider for application/json ContentType.
type CreateServiceProviderJSONRequestBody CreateServiceProviderJSONBody

// UpdateServiceProviderRequestBody defines body for UpdateServiceProvider for application/json ContentType.
type UpdateServiceProviderJSONRequestBody UpdateServiceProviderJSONBody

// CreateUserRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// InitiatePasswordRecoveryRequestBody defines body for InitiatePasswordRecovery for application/json ContentType.
type InitiatePasswordRecoveryJSONRequestBody InitiatePasswordRecoveryJSONBody

// ResetUserPasswordRequestBody defines body for ResetUserPassword for application/json ContentType.
type ResetUserPasswordJSONRequestBody ResetUserPasswordJSONBody

// UpdateUserRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody UpdateUserJSONBody

// ChangeUserPasswordRequestBody defines body for ChangeUserPassword for application/json ContentType.
type ChangeUserPasswordJSONRequestBody ChangeUserPasswordJSONBody

// UpdateUserStatusRequestBody defines body for UpdateUserStatus for application/json ContentType.
type UpdateUserStatusJSONRequestBody UpdateUserStatusJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List All claims
	// (GET /v1/api/claims)
	GetClaims(ctx echo.Context, params GetClaimsParams) error
	// Create a Claim
	// (POST /v1/api/claims)
	CreateClaim(ctx echo.Context) error
	// Delete a Claim
	// (DELETE /v1/api/claims/{id})
	DeleteClaim(ctx echo.Context, id int) error
	// Get a Claim
	// (GET /v1/api/claims/{id})
	GetClaim(ctx echo.Context, id int) error
	// Update a Claim
	// (PUT /v1/api/claims/{id})
	UpdateClaim(ctx echo.Context, id int) error
	// List All scopes
	// (GET /v1/api/scopes)
	GetScopes(ctx echo.Context, params GetScopesParams) error
	// Create a Scope
	// (POST /v1/api/scopes)
	CreateScope(ctx echo.Context) error
	// Delete a Scope
	// (DELETE /v1/api/scopes/{id})
	DeleteScope(ctx echo.Context, id int) error
	// Get a Scope
	// (GET /v1/api/scopes/{id})
	GetScope(ctx echo.Context, id int) error
	// Update a Scope
	// (PUT /v1/api/scopes/{id})
	UpdateScope(ctx echo.Context, id int) error
	// List All serviceproviders
	// (GET /v1/api/serviceproviders)
	GetServiceProviders(ctx echo.Context, params GetServiceProvidersParams) error
	// Create a ServiceProvider
	// (POST /v1/api/serviceproviders)
	CreateServiceProvider(ctx echo.Context) error
	// Delete a ServiceProvider
	// (DELETE /v1/api/serviceproviders/{id})
	DeleteServiceProvider(ctx echo.Context, id int) error
	// Get a ServiceProvider
	// (GET /v1/api/serviceproviders/{id})
	GetServiceProvider(ctx echo.Context, id int) error
	// Update a ServiceProvider
	// (PUT /v1/api/serviceproviders/{id})
	UpdateServiceProvider(ctx echo.Context, id int) error
	// Retrieves the existing credentials
	// (GET /v1/api/serviceproviders/{id}/credentials)
	GetCredentials(ctx echo.Context, id int) error
	// Update a Client
	// (PUT /v1/api/serviceproviders/{id}/credentials)
	GenerateCredentials(ctx echo.Context, id int, params GenerateCredentialsParams) error
	// List All users
	// (GET /v1/api/users)
	GetUsers(ctx echo.Context, params GetUsersParams) error
	// Create a User
	// (POST /v1/api/users)
	CreateUser(ctx echo.Context) error
	// Initiate Password Recovery
	// (POST /v1/api/users/recover/password)
	InitiatePasswordRecovery(ctx echo.Context) error
	// Reset password, after recovery
	// (PUT /v1/api/users/recover/password)
	ResetUserPassword(ctx echo.Context) error
	// Delete a User
	// (DELETE /v1/api/users/{id})
	DeleteUser(ctx echo.Context, id int) error
	// Get a User
	// (GET /v1/api/users/{id})
	GetUser(ctx echo.Context, id int) error
	// Update a User
	// (PUT /v1/api/users/{id})
	UpdateUser(ctx echo.Context, id int) error
	// Change Password
	// (POST /v1/api/users/{id}/password)
	ChangeUserPassword(ctx echo.Context, id int) error
	// Update status
	// (POST /v1/api/users/{id}/status)
	UpdateUserStatus(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetClaims converts echo context to params.
func (w *ServerInterfaceWrapper) GetClaims(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClaimsParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetClaims(ctx, params)
	return err
}

// CreateClaim converts echo context to params.
func (w *ServerInterfaceWrapper) CreateClaim(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateClaim(ctx)
	return err
}

// DeleteClaim converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteClaim(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteClaim(ctx, id)
	return err
}

// GetClaim converts echo context to params.
func (w *ServerInterfaceWrapper) GetClaim(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetClaim(ctx, id)
	return err
}

// UpdateClaim converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateClaim(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateClaim(ctx, id)
	return err
}

// GetScopes converts echo context to params.
func (w *ServerInterfaceWrapper) GetScopes(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetScopesParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetScopes(ctx, params)
	return err
}

// CreateScope converts echo context to params.
func (w *ServerInterfaceWrapper) CreateScope(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateScope(ctx)
	return err
}

// DeleteScope converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteScope(ctx, id)
	return err
}

// GetScope converts echo context to params.
func (w *ServerInterfaceWrapper) GetScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetScope(ctx, id)
	return err
}

// UpdateScope converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateScope(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateScope(ctx, id)
	return err
}

// GetServiceProviders converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceProviders(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServiceProvidersParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetServiceProviders(ctx, params)
	return err
}

// CreateServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServiceProvider(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateServiceProvider(ctx)
	return err
}

// DeleteServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteServiceProvider(ctx, id)
	return err
}

// GetServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetServiceProvider(ctx, id)
	return err
}

// UpdateServiceProvider converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceProvider(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateServiceProvider(ctx, id)
	return err
}

// GetCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GetCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetCredentials(ctx, id)
	return err
}

// GenerateCredentials converts echo context to params.
func (w *ServerInterfaceWrapper) GenerateCredentials(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GenerateCredentialsParams
	// ------------- Optional query parameter "refresh_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "refresh_id", ctx.QueryParams(), &params.RefreshId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter refresh_id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GenerateCredentials(ctx, id, params)
	return err
}

// GetUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetUsers(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUsersParams
	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", ctx.QueryParams(), &params.PageSize)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_size: %s", err))
	}

	// ------------- Optional query parameter "page_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_number", ctx.QueryParams(), &params.PageNumber)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page_number: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUsers(ctx, params)
	return err
}

// CreateUser converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUser(ctx echo.Context) error {
	var err error

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateUser(ctx)
	return err
}

// InitiatePasswordRecovery converts echo context to params.
func (w *ServerInterfaceWrapper) InitiatePasswordRecovery(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.InitiatePasswordRecovery(ctx)
	return err
}

// ResetUserPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ResetUserPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ResetUserPassword(ctx)
	return err
}

// DeleteUser converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteUser(ctx, id)
	return err
}

// GetUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUser(ctx, id)
	return err
}

// UpdateUser converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUser(ctx, id)
	return err
}

// ChangeUserPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ChangeUserPassword(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ChangeUserPassword(ctx, id)
	return err
}

// UpdateUserStatus converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameter("simple", false, "id", ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set("OAuth.Scopes", []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdateUserStatus(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET("/v1/api/claims", wrapper.GetClaims)
	router.POST("/v1/api/claims", wrapper.CreateClaim)
	router.DELETE("/v1/api/claims/:id", wrapper.DeleteClaim)
	router.GET("/v1/api/claims/:id", wrapper.GetClaim)
	router.PUT("/v1/api/claims/:id", wrapper.UpdateClaim)
	router.GET("/v1/api/scopes", wrapper.GetScopes)
	router.POST("/v1/api/scopes", wrapper.CreateScope)
	router.DELETE("/v1/api/scopes/:id", wrapper.DeleteScope)
	router.GET("/v1/api/scopes/:id", wrapper.GetScope)
	router.PUT("/v1/api/scopes/:id", wrapper.UpdateScope)
	router.GET("/v1/api/serviceproviders", wrapper.GetServiceProviders)
	router.POST("/v1/api/serviceproviders", wrapper.CreateServiceProvider)
	router.DELETE("/v1/api/serviceproviders/:id", wrapper.DeleteServiceProvider)
	router.GET("/v1/api/serviceproviders/:id", wrapper.GetServiceProvider)
	router.PUT("/v1/api/serviceproviders/:id", wrapper.UpdateServiceProvider)
	router.GET("/v1/api/serviceproviders/:id/credentials", wrapper.GetCredentials)
	router.PUT("/v1/api/serviceproviders/:id/credentials", wrapper.GenerateCredentials)
	router.GET("/v1/api/users", wrapper.GetUsers)
	router.POST("/v1/api/users", wrapper.CreateUser)
	router.POST("/v1/api/users/recover/password", wrapper.InitiatePasswordRecovery)
	router.PUT("/v1/api/users/recover/password", wrapper.ResetUserPassword)
	router.DELETE("/v1/api/users/:id", wrapper.DeleteUser)
	router.GET("/v1/api/users/:id", wrapper.GetUser)
	router.PUT("/v1/api/users/:id", wrapper.UpdateUser)
	router.POST("/v1/api/users/:id/password", wrapper.ChangeUserPassword)
	router.POST("/v1/api/users/:id/status", wrapper.UpdateUserStatus)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9/W4bObLvqxC6F9gZrCx/xPHMeHCB9dqeXO9NYsOO72JOYjhUd0nipEX2kmw7moGB",
	"fYV9xX2SgyqS/cmWZMf2ZA72n8RSk8ViVbHqV0Wy9dsgUfNcSZDWDPZ/G2gwuZIG6MOlPCjsTGnxK6T4",
	"OVHSgrT4J8/zTCTcCiU3fzFK4ncmmcGc41//W8NksD/4X5sV8U331Gwea6304O7ubjhIwSRa5EhksD84",
	"zARIy4RhhWS8HJhZxXiSgDHMzoBp+EcBxg6wvyeJIx7OuJzCGTfmVun03Dfa/601xgFLqCHLfctAj6nx",
	"L5DYwXCQa5WDtsKJQMLtdWjbJfduBkzCbUXNKmbAjgbDwUTpObeD/UHZeziwixwG+wNjtZDTwd1woLJ0",
	"BXWVpUxpBp+FsUJOWY3aGiPcDQc4P6FRf++bww2bc7sqO3tJ3A0HhxkX86gQ8QFLlJyIaaHJCvoE2Oja",
	"pWRmSluWgg7fMj5WhSVV0yijmNxERFon0oKWPGMiBWnFRIBmalIRqugIaWEKGglJPocYWzzLZ1wWc9Ai",
	"YdhoiKrVkGswaKROAPiACclOcZns9PLb0gKNSXPolfkZnxJbPMtOJ4P997+1hEojdcU74JJxrfkCJ+7b",
	"DAfCgmu7bFU6Vd+VDBGZDuueZoTv5dRpPndXw46ccz716jGMGxa8D5toNWcHZyeDiIScA+kqTTLAJxWR",
	"h1jkEVguMlb/MmJ/EGeBOGOJSiFqBJ2ZBDU3+UOZXMtiPobIENiFuYfBusv5JrNCfqo7BiHti52o3dMY",
	"VlmeRdwOfs34DRcZH2dAOjLrkG0ZS30ejRFjZn+RqDy6Ev3acs8f0bkYJPgYzsV4ztZ1LjQTch2jpptJ",
	"ZlzzxII2TMls8aWO5AL0jUjgTKsbkUJ8wbjWlV/DCKMkMOP6stx3HnUkX4v/127oNvn/J2QaZFRrPWIY",
	"1lKY8CKzQyYmTM2FtZAOMfLfwrhsICSk7IZnBRjGNYrMihvAaEit/g5j5iCDYYVBznEkMhd2MsfxhGWv",
	"NJeWvVvkwN5cXrwjwTINU2EsaHZ5/rred2Ztbhj5LHDeKBUaEntdaGF+xCYLR+Xt6TtWGGCZSng2U8Zi",
	"a6KgjHWafeuYDQxGBm9Q91wkhbFqzi7PTzwbBqcbYXM/sHkr7GwZHwHAuRiNNoH29ebgZ5ZnPAHG01Tg",
	"I55hODdWc4H8KtmawTJKGsiKzv2E8DHOwKuuybjne8iUnYFmdsYlPaumkHD0/0p3GECziDHhhHsDWkwW",
	"SNAynmXeMzpZQ9qSNiIXpecY0+0M0HVWc8eBhGG5hhtSnZlxXH2Me07YyRHjiVbGsFRMJqDxO1wCBq09",
	"cDsYDkAWc1ymtzBGsEWzqa3UyuFM0UhpFUVC+t8uTt/6oI7wmwvpmMkEgtZJzeh3Rls1ezdOFPi4AtYp",
	"JJmbDT0Ult2KLMMIYrVI8AsD2QTFQlpzMq+toVKlkLLxgn2QH+RpDvLkiB0qKdEIuIb9D3J7VAJ45yIw",
	"Ju5HNHio0sYAbu5jSEtYRdO68Ga1O9oeEXXhF7ijGVvuKyntOEoaJhrM7NqqTyAduXP3FXuHX92D5t4I",
	"BYIUJirL1C3JmUIoKsutzERpF69TkAmwMdhbAFnGcLKCIOa2AklX6He4TFllNI3mtBbGiEqTrEgdp62l",
	"UDM3Ymwfud4eMaejrt6cwNMgoSB6+pq+63uInWvPupSHkfb3b7z2EB/kSS3a2CoM4dLoFTZ5bQpiHeI1",
	"2xjVgXZnhTdBdR8yeIvphF/SngurUJk+OrtcGJ8ey3Tj0oAesZMJWiUigmEVxn1ChpSEYQTt0Q4qd5Vx",
	"OS0Q1pEpOR4MSqEkASnGkobBBzPfGW1HcVPDxUbgRkhMeuOEcyrV7EfsVAaBmIYJ95Ag44fPPLHZgs25",
	"TWbe9ivGWM41nwMGYOrkhhWSAU9mLefkqwhDF2SREtGkNBw0BpAlUtob7Yy2kfn35z8dvvjh+70r9s0F",
	"2iKwCxIZO1TznGthlPz2PtbTAoFNqTeDybAL09ZAiocaCOTyzMRrEknVgIkRjNjHhPR1LdKPZFDhs4FE",
	"g/3YRY9l++4AIViVODtmag36vTT844dUSpoDDGsMryHAi2I+53rxyIg7mpZ0spF6/xX52b0ms6oi4fm/",
	"DuOb6OzL4kR7usy4YXAFoTgwWxytW7voEf+qldNl+dHqGvfTc0cF6NqXCZunqQazUi5I5sA3vRsOxkLb",
	"WcptJPKEePInw3yrxbAdC7hkJxen7Pu9re39na2tXfb+5OIUP/37n//Cz1fs559//nnjzZuNoyPmVpzD",
	"jwvgmvKEMbCtra2tIRMyJadUw6HChMg8Yu/qlbYy/CKZIY3hqWMfjjgL+7xVFhyxFHKQqZM3dSxkCjpb",
	"kNvOuMXOfzIMBcE0ZBynNykkee2h1wu2/aUw1vGecAJoBBQku+GaaM2VtDNydyQt4yIzefg5Ck0bJsGH",
	"bP4JXCye8MQqzYR0RW1VuBhPqJCiVq5VWepGFk2jlkzai2UQIKMpfk2vrsmI/X8XKkN+TQFXGGZySMTE",
	"hwpKtycw55nDmvjHiJ1SxhZCrdMnRc/bGUgmQdBz74ci+buPReNs/bIL8l4LBaNomYVSx+VG7Zp0TZr9",
	"9fBs9zsK0S/3dveuSmDELJ/6RBCx4SIXCc+yRVgEey9+2NhmB1k+4xs7tBD2Xvzw73/+a7tGwaFfydBA",
	"NSW1KEpP4MX23l6LAn7lSJBZ6EVJochzR2HIDCB+sU5xnKXczEbsJ9og4Gh5QwZy4/KCKc0meuPwYMQO",
	"cJroHLgVY5EJu2BSWSSl5jVzJb0bNuM3XqlcuoVjEqUh1BX88Eozzav83fExpKS9xsf15cWP7Bzcyjvj",
	"5L3IbpKZUgbCvk5unQU6HTGzkJZ/xgFvIcuillIY0HEEfemfECuZmopo9fZXJUHIiYrU5hwyo+pzaMXe",
	"h7+umBVzoAe4NvmYEyqtefg6Nv+TqZq3dHRcoDvfPEP0h6o6oAIg33ytzPWBnELmlv1yiFJKoa8CuDo4",
	"YMKxVsMzrSYiW6/toZKWr8lAGZ0iWwOpq8TjNEM0FdJ5wkZVvhk2D6rQ2OsNcg0T0JhH5MpQrdt1cuHK",
	"pQWhcOmesDlQxR0jDqOKDLqM3b2d766YsbpIbKGhXp+hxaU0VaI8KUei8ry1XOHlaNvlVC2U7PxABN96",
	"B0GmXoo2ulacwCxEnOtPRZaxORcZFZTcRIes7EBrKBUmzxCyaZ8LM152yfgYMu8kJwKy1C1uJwQ2LzIr",
	"cqp9SDAtzyXhlr4esbf+LwqyY2h4aB9RyFEnXGuBblWDLbTcxE5sgvE150Kzbz4MPnzQHz7ID4NvSe7Y",
	"xwg59Qy4pmWF3bXHxlGhkSsSNiZ59J/kW1yLFdJ39kW1gi6t/xK5c/FKB0Okj8tJYhYc2+24sBy9OuEX",
	"mdBfMAEyzCGjXTHst4K4sRrAXvO+RUQm4xqVS6OkOGS3M5HMyAp8+YnNFJqN2wQahp5uP/VMGctOJxNE",
	"w39Vn4cOaaDVbJDG4LNFyJK2x6s5gf+BxnfX49eCV41DpMQ9Jdl03Ajggl3TIcIGNq4c4ok13iFSbaVZ",
	"N2fnPx2yly92dhyAerGzc0U9NxBM+kDufOr5WbVxoiFbsCIncC4C9TGgRymk+EcBQ6qpCJMUxrT95HdR",
	"s6UZXtMOgIh5une6ACYm7fDcnCybccPGAJIFQj+6TYpbYYBNeGZgxP6OULdWVSM0TRBRI+P0ZA5c1uqJ",
	"p2fMKvWJ8clEkN3eADMWcoNSBGkwcvjGosPTLafNCqtVllXlsTAH5ocgnIF/OM49iMe+ZZ3K6cGxNl74",
	"lcplezxUiJ89c/skFj7bjZAduEXqMixMzrwaAadvLJtoPodbpT8x5WwSDb7AADvVQDDTUC1NSM8AVSw8",
	"MsQUAc2W8sKamsdKZcAludOZkv1b41GDtpABdfNOaMSOR9t7u+w9/XeFkzw/Pjx98+b47dHxUcC5PsFs",
	"VFBb+PbP2+yb3Z2X37KXL19ubO9s7+Cc//xyj32z8y3b+/47trO7tUX1WZpkjYXgpSilJi9nKPV0WXCd",
	"m9KGylZtL1VtruFafPHD3p6vN+7tXdV6ubUYmcHe1m6YwYvdH+Gz/T8v9777Ph7LasJfstYexS6b8vpq",
	"jNIvf7/UvVa9SLxDqPZfvKF5U3K536LSiSmb1vUpZKVIX0OJrIS+IPG25zRTSBWYdZZHRVVvB9h+Km5A",
	"XruUajAYDkyhw4e7djSZ8LnIFtc9Zxtcx28MxcGMGxfs6fOktXNRVWyEdHg5KTKEK2bIclAYvTEsU0Za",
	"xnM3OhGlzEmq+lc/Et72wdwLtVa9d71cqGkgApPzBGrnL6L2XxdSe96v8BmrTX0i9KPPfVoOYp50onOR",
	"phn0zPQNPXzkmc0roo83NXaQGUW1jj5+6sO6EybKUvEjKpa4PGpBZ4LgOBwJ9IkT7f4SZHKImFKt0Ayd",
	"DIpFGSPG2aLWxAqbhc25YjIRn5FdpVPa/OJJorRrptqQxhdRsKOLgSATiKtZiuRTfE6H3KB/lLXtyBJx",
	"kCjnLiPE/1BkY+fkDZ+XhaJqsbjSh5DGckpLOAsDV5n2G/EJjWA6s84fIsjGiWZKTo1IgfEawXq3ZMYh",
	"XiMqEcB1f7XoYqa0naGsiG4ZfhoTvhVmBsZvxFawQoUYd342ZKbAoGXYL1xCqiih+2WUKvD5iQfQrmKK",
	"QeCGZyJ1dQTHcU31FNUwFaxOgwXyfxmyTcrlbmfCAhn8A+B1T9KBFjfYH5wr5Q87IFYog0pPwAl1oXV3",
	"uqiYk7tOlKyYbtUjF5S0RpDF+eu2ORLUc9R8Ny9ybEsiIY2RuiQTc8zhqPU3DSTE2dnbV0P2t7PjVyTf",
	"Vyc/1Rp/O2xUO5EWHT5zZ1drZ3L8CHUnaAMzF//39PL1UVVmz+gomF+gCHjCNGbKqs6qM4WwwZUE14JD",
	"UuXdbz+3649Nrulk8FhYzfXCD2L5J5DtlKJnMfWoeYVKSBi0Y+wuDpgSUZfy83LBhVEezVzKyy2MjbBr",
	"81IOpDQbZyoU9dvjh8JBrbjA8mKc4eLvpl2Y40um9JTLcFaghOplI2Eo5csERSgMYPdI988hUTegz3rv",
	"Bhw0Li6gUQopLI5Vv9pARBZrVwQoFRTlqU1arbQ7JTF1dUGYvjRWaXhgab5G/D41bsfzVa+8DNjl0jJg",
	"O7c+OpJRNu/2PpU+lalLFsQNxoGZVsV0FoRPZuN28J5BOshsjWifbC4st4W5zONbvwesoCfMULNeyfCE",
	"zi92Dy3BbeiKpuJu11jVk7bU2fcUe9nuPUVRHhboHniq7RY0U5zAPiVvg3Gmkk/IBZV1gnHtkyy3/5Kq",
	"ORdylKh5Xbz+aTcj6pNM6QWScG5ZSN82Vtwoeeqj4xugNxLSQQhuLcxzG6W3dJGHCu+9jPS1mgrJamvy",
	"PjAiqHO5tlcdM8HBTfRGksoyXyX0ZrD21Zc6d6vOjDjCj3z/JditKUVUM9zGbZCXu82rG3vbwyCS9702",
	"7j4GE6ccyMJn27Tt6mucyyNRuuqGt7vhwEBSaGEXF+6EO06SztLGDpsJg7auMg+5SRGMh8iE+IX2aumf",
	"BPQYdGH8KWaEYXpOQGvG8xykcXBpoQq3NUwU07mQ7NXlCfordzQdVxFwXfe/M2tzd2MxbBsnVTk+iCPX",
	"3ID8Rdi/lH+NJB0e84I5C1+zs0KrmSC56czTN/ubm7e3t6Nm5+4lyTDJA+L84OzEjNgRGDGVTkZU6aJI",
	"XckDk68s80c7ZFo7pELeJDTc4LloXNUYDAeZSEAaskQ/jYOcJzNgO6OtKP+cHo+Unm76vmbz9cnh8duL",
	"4w3sU3MS9XEHw8ENaOMmuT3aci1VDhIf7g9ejLZGO3SNyM7IZDZvtjd5Ljb7rsJRXnR88Y6BTHMlpN3E",
	"ru5sg1Xu+DzKItGA0e9X0IpyWqWBfaRa3keGWQt6nhHzdwKQQlW9ZR9fHb/zJx7PTi/efQylQkW25Wuc",
	"7npDazjLzSczpGPfQGvN3feZxk4zvgJragf+eZZ1GRyQrNzYJ6nrdBguAJZHXp2baMXv8i4ZOcvyKCyB",
	"9w/yyJ+QvgkbHdtbdC4Pu/6jcODSGwY5JiN+hbCUeO00a+0Q4rIrbXTJEtN/5CMcih99kBeWa1+nZdu+",
	"3ttmjFmllvJW3kVbwt3VsHkFemdr69FuPldXOyO3ny8KuuM8KbLqQt+GF4Zh9YudXeWTVw1wafAaDeUg",
	"y6oboJZPDZ14LHJcbyQDdyf2ym9SR4pAZKhoeBJuy/oNGWDgoGt1rtOhv27roeRfVbp4XBnG5HdAfAbZ",
	"uHKNW2xUzquCOAaxu46Wt2PF7I5G2qJ286WrQf6G8VJJVx3P6r5oziUdOQt+ory8O0If2HR0m7+J9M7x",
	"mkEMzx/R935vyV8a79WXa1zpqyGS3QeJxJFcWyT3ctpTsEOfroRNHxrM77UHI6UyA5fltKPem3z3kH08",
	"u8T/yIcfHb8+fndc8+KmHLnuy/u4uLdPd+ckLReZ47g9jxWLLbj4wVO7rAe4qzCVkvmmkbwCu7aFLI1e",
	"B76oWb+XixlHQ2wUEFD7VTwQaccnrAoLeRE7fUFmsOZqc41/F+/ohk5L/1g/RLOGd9x5kCtwgz6SdyxN",
	"6tC9ZaHmGekG9mNDQLqm/TVDwDaDMf9w4STzHwj4nBBwvTsr9NaAbrnhS3BhxyJ6cKEJVhFbj+51Bg/E",
	"hY6DPlwY3uHwFJ7Py7MXF3rZPDcuDFNeLun1caFTXcT7PQwX9unLNa709Zi4cD2RPCku9NP+g+PCPuUF",
	"v/+UuLB3ua2LCwPzMVy4noU8FBdWYntuXNinMNf4d/GOJS70/vF5ceFjeMfSpC7cC33qntHdtVxyJfXL",
	"EGLz2ulXjRV7WY16j2br/+DHr6eEuORy9hdix34L6UOR7dVVW8fu0UZ4RkdKw9J+KLRsMdgLMluvvXoi",
	"h9oaZQnwbAv22SFoRyBrq+keuLRlDEv98AOx6koD8Kg1YgCPil8fLs+nBbVt+fzR4e1KfXdD1eD5XO8X",
	"gd/O1KIw+OGG9mBsHJH5s6PklXr3ePlrcfQVhm67+mdG00/l6CuI3RxhtZPfTFa9S2ipA5SodWBJeCWQ",
	"OxBP7+ShoNO77YPt+xwger5+5O1fB9frwYjiwdkJrmot4AaMv6Dlzbf+bqTypQmtd93MeHjJIBJKuGRS",
	"ZQtCBZyu+bnVmGtxQwfzIq+M6e4E1QT9fE6wPmrMH4J7b/e5Z6dluecrRfgcPi9Yy++yUVQO3VaoM/2m",
	"VpfO8MS9UwfolJM/+K2COfu3YPt3WOE6kcqO2FH1+ruPdBLyY1/yE96SSOLoTL864XnV8cKtVFGV55bH",
	"2ODu67HVYqmt1vayUIp9RYu2ka52rpW1N8CQfwNe3cP2nH38ohrGpfm6Cxct/mKe79L8p0TxNZUo2qd5",
	"v6wu0TaAnmJEOPAbW5RfUnWg4ftKDZfmyWAnke4vKjipPHclwc93qYzXLxmQyroObtPfWtlc9rsYHR+F",
	"hA/OToxbWkTA3+P2NzZInQVdi/JvxDXCFv5CunupQ621MIgOpspaIOQet5wTf+PGdK7c0IVU/xY6evvW",
	"vJDh+nu4MuLvZ6atx8mMSwlZx+TCYNVPnJSXe57KANuXkCL2eBK5dBTuj6yyxq3Yi42kf0mGkowOVqMY",
	"m8fG0bujA6ssrWQicMpqwgnWyqWSi7kqTMMjxKDaaT24te4N8YkFRI2mvmzcWLXLGE3N0d0kui1ZvX30",
	"6VRWvwcVUdh53z2oB2irC5mGg13XMMZnSXCz8btCy3Xb5HfoFaDX1G/XG+nVHqLrkh5Ur+wJHa5tGToe",
	"szK5jn9+0hKkm/IfvO7YozePNAdPjJy+pKzoOY/VEpeYBpeLDlB6YCpdiu65E+kenbm2vwNMK0uCDqg9",
	"bx3wy2FaaVLuFnbUH24u/92yhleh33TzQ/jbpm3XW943rt61DnamQsY5WpXgFe5NsY9ne/FcwV1vda8x",
	"qKJ5KzmgRs8Q8OO/eRf7Zb34b959kSm2ov72Q6J+lWI4BmvyqsL6YrXt6trV46Zu4qbr7is/3HD9fec/",
	"jNnSO4BzDTcig3RKrw3DRCg6I/e7PD4563eo7lL5E7rVxq31WCZMkQ99m1NAXf10fdW9KvvRYO29DRw7",
	"vfiiVXFZv5h/f4/eWRWeUBtwh9u376/Qgvwg5XVPP07kSrp7ebqmn+m7G5YdIoX69q5Aaz8kvIW9Tcif",
	"Dov9fFpPl/BDj+2fg+Bi3telnjdEfn6zzAWFK0yF1tWTBss1zawgBp8hKcKbQdwaDJ3DG+7ca5xAz4Ux",
	"rYEqt3jvYZaOcHX33wEAAP//qw8NcRF2AAA=",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
